package com.example.orientation;

import static com.codename1.ui.CN.*;
import com.codename1.ui.*;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import com.codename1.ui.plaf.*;
import com.codename1.ui.util.Resources;

import java.io.FileReader;
//import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.Hashtable;

//import org.json.simple.JSONArray;
//import org.json.simple.JSONObject;
//import org.json.simple.parser.JSONParser;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class PomonaCollegeOrientationApp {

    private Form current;
    private Resources theme;
    public boolean HideFirst=false;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if (err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });
    }

    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form Main = new Form("", BoxLayout.y());
        TextArea menuBlurb= new TextArea("Click on each menu item to see more." +
                " Click again to return to the full menu.");
        menuBlurb.setEditable(false);
        menuBlurb.setFocusable(false);
        TextArea welcomeMessage= new TextArea("Welcome to Pomona College!");
        Font QuicksandBold=Font.createTrueTypeFont("Quicksand Bold", "Quicksand-Bold.ttf");
        //welcomeMessage.getUnselectedStyle().setFont(QuicksandBold);
        welcomeMessage.setEditable(false);
        welcomeMessage.setFocusable(false);

        Main.add(menuBlurb);
        Main.add(welcomeMessage);
        Button submit =new Button("submit");
        submit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                HideFirst=true;
                System.out.println(HideFirst);
                System.out.println("hullo2");
            }
        });

        if (HideFirst) {
            System.out.println("hullo");
        }
        Main.add(submit);
        Main.show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }

}

